### ISSUE TITLE
less @import时会报错，运行目录没有设置，是主程序的运行目录

### ISSUE THREAD

**Issue by feix760** [JacksonTian/loader#21]
less文档：
less.render('.class { width: (1 + 1) }',
    {
      paths: ['.', './lib'],  // Specify search paths for @import directives
      filename: 'style.less', // Specify a filename, for better error messages
      compress: true          // Minify CSS output
    },
    function (e, output) {
       console.log(output.css);
    });

lib/loader:
      // 调用less将源文件内容翻译为CSS
      less.render(content, function (err, css) {});
      可以在此处用第二个参数指定路径信息

**Comment by JacksonTian** [comment]
是上下文还不够对吧

**Comment by JacksonTian** [comment]
建议不去用@import语法。
