### ISSUE TITLE
请问在Jade 中 怎么调用 loader

### ISSUE THREAD

**Issue by ThomasLiu** [JacksonTian/loader#22]
我尝试过 
Loader('http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css')
                .css('/public/stylesheets/style.css')
                .done(assets, config.site_static_host, config.mini_assets)

script(type='text/javascript').
        Loader('http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css')
                .css('/public/stylesheets/style.css')
                .done(assets, config.site_static_host, config.mini_assets);

- Loader('http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css').css('/public/stylesheets/style.css').done(assets, config.site_static_host, config.mini_assets)

都不行……

**Comment by JacksonTian** [comment]
在jade中怎么调用一个函数？

**Comment by ThomasLiu** [comment]
在一些网上的教程上有这样的代码

script(type='text/javascript').
      if (foo) {
         bar(1 + 5)
      }


所以觉得应该可以吧…… 

那您的意思是 使用Jade的话，就不能使用您这个loader.js ；来管理？

**Comment by JacksonTian** [comment]
不是前端函数。

**Comment by JacksonTian** [comment]
Jade的用法是这样：

```
!=Loader("/assets/cssmin/base.css").css("/assets/bower_components/framework7/dist/css/framework7.material.css").css("/assets/bower_components/framework7/dist/css/framework7.material.colors.css").css("/assets/css/font-awesome-4.4.0/css/font-awesome.css").done(assetsMap,CDN)
```

**Comment by zhaoshiling1017** [comment]
请问一下朴大，在Loader加载less文件时，如果less文件包含@import标签，在builder的时候会报异常，这个问题该如何解决？

**Comment by JacksonTian** [comment]
不要用@import 。多写一个.css('xxx.css')不就好了么
